version: "3"

services:
  tinymediamanager_service:
    build: .
    container_name: tmm
    network_mode: host
      # ports:
      # - "5803:5800"
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=Asia/Shanghai
      - VNC_PASSWORD=pa5sw0rd
    volumes:
      - "./config:/config:rw"
      - "../media/downloads:/media:rw"
